name: Release

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Rename binary
      run: mv target/release/gut target/release/gut-linux

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-binary
        path: target/release/gut-linux

  build_macos_x86:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Rename binary
      run: mv target/release/gut target/release/gut-macos-x86

    - name: Upload MacOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-x86-binary
        path: target/release/gut-macos-x86

  build_macos_aarch64:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Rename binary
      run: mv target/release/gut target/release/gut-macos-aarch64

    - name: Upload MacOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-aarch64-binary
        path: target/release/gut-macos-aarch64

  release_all:
    runs-on: ubuntu-latest
    needs: [build_linux, build_macos_x86, build_macos_aarch64]

    steps:
    - name: Download Linux Artifact
      uses: actions/download-artifact@v2
      with:
        name: linux-binary
    - name: Download MacOS (x86) Artifact
      uses: actions/download-artifact@v2
      with:
        name: macos-x86-binary
    - name: Download MacOS (Arm64) Artifact
      uses: actions/download-artifact@v2
      with:
        name: macos-aarch64-binary

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
            gut-linux
            gut-macos-x86
            gut-macos-aarch64
