name: Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Rename binary
      run: mv target/release/gut target/release/gut-linux

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-binary
        path: target/release/gut-linux

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-binary
        path: target\release\gut.exe

  build_macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Rename binary
      run: mv target/release/gut target/release/gut-macos

    - name: Upload MacOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-binary
        path: target/release/gut-macos

  release_all:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows, build_macos]

    steps:
    - name: Download Linux Artifact
      uses: actions/download-artifact@v2
      with:
        name: linux-binary
    - name: Download Windows Artifact
      uses: actions/download-artifact@v2
      with:
        name: windows-binary
    - name: Download MacOS Artifact
      uses: actions/download-artifact@v2
      with:
        name: macos-binary

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
            gut-linux
            gut.exe
            gut-macos